name: Hello_workflow

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello word
        run: echo "Hello github"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye see you later
        run: echo "Goodbye github"
        shell: bash
